server:  
    # 设定http监听端口
    port: 80
    tomcat:
      uri-encoding: UTF-8
  
# Jedis 
jedis: 
  max.total: 100
  max.idle: 10
  max.waitmillis: 10000
  testOnBorrow: true
  max.timeout: 10000
  host: localhost
  port: 6379
  
  
